

def get_cpcs(state_abbr: str) -> list[str]:
    return [
        "a woman's haven, inc.",
        "abba women's center",
        "abundant life pregnancy resource center",
        "adria women's health",
        "agape pregnancy resource center",
        "aggieland pregnancy outreach, inc.",
        "allied women's center",
        "amistad pregnancy care center",
        "anderson house pregnancy resource center",
        "angels clinic",
        "any woman can",
        "bastrop pregnancy resource center",
        "beltway 8 s crisis pregnancy center",
        "birth choice dallas",
        "birthright of beaumont",
        "birthright of houston",
        "birthright of humble",
        "birthright of odessa",
        "birthright of orange",
        "brazos pregnancy center",
        "bulverde/spring branch pregnancy care center",
        "care net pregnancy center of borger",
        "care net pregnancy center of central texas ",
        "care net pregnancy center of dalhart",
        "care net pregnancy center",
        "central texas pregnancy care center",
        "choices clinic",
        "clear choice pregnancy resource center",
        "cleburne pregnancy center",
        "community pregnancy center of pasadena",
        "compassionate care pregnancy center",
        "crisis pregnancy center of victoria tx",
        "dumas area crisis pregnancy center",
        "eagle mountain pregnancy help center",
        "east texas pregnancy help center",
        "expectant heart pregnancy resource center",
        "fannin pregnancy care center",
        "fifth waroad pregnancy help center",
        "first choice pregnancy resource center",
        "firstlook clinic",
        "for her women's clinic",
        "fort worth pregnancy center",
        "heart of hope",
        "heart of texas pregnancy resource center",
        "heart of the hills",
        "heartbeat pregnancy center",
        "helping hands pregnancy resource center",
        "highland lakes pregnancy resource center ",
        "highland lakes pregnancy resource center",
        "hill country pregnancy care center",
        "hill country pregnancy center",
        "hope center",
        "hope choice canyon",
        "hope choice center city",
        "hope choice medipark",
        "hope pregnancy center",
        "hope pregnancy centers of brazos valley",
        "hope pregnancy centers, inc. ",
        "hope pregnancy centers, inc.",
        "hope women's center",
        "hope women's resource clinic",
        "horizon pregnancy resources",
        "houston pregnancy help center",
        "inspira resource center",
        "involved for life",
        "laredo life pregnancy center",
        "life choices medical clinic",
        "lifetalk resource center",
        "living alternatives of palestine",
        "loreto house",
        "marshall pregnancy resource center",
        "mcallen pregnancy center",
        "metro family pregnancy center",
        "metroplex women's clinic",
        "mid cities pregnancy center",
        "new beginnings pregnancy center",
        "next step women's center",
        "nurturing center",
        "open door pregnancy help center",
        "options clinic",
        "options for life",
        "paris pregnancy care center",
        "parkridge pregnancy medical clinic of lubbock",
        "pregnancy assistance center north",
        "pregnancy care center",
        "pregnancy help 4 u",
        "pregnancy help center of concho valley, inc.",
        "pregnancy help center of el paso",
        "pregnancy help center of fort worth",
        "pregnancy help center of lufkin",
        "pregnancy help center of west houston",
        "pregnancy help center of williamson county",
        "pregnancy help center",
        "pregnancy lifeline",
        "pregnancy resource center ",
        "pregnancy resource center east",
        "pregnancy resource center of grand prairie",
        "pregnancy resource center",
        "pregnancy resource medical center of fort bend county",
        "pregnancy resources of abilene",
        "pregnancy support center & hope house",
        "prestonwood pregnancy center mobile unit",
        "prestonwood pregnancy center",
        "radiance women's center",
        "raffa clinic",
        "s austin pregnancy resource center",
        "s texas pregnancy care center ",
        "san antonio pregnancy care center",
        "sealy pregnancy resource center",
        "someone cares advocacy & pregnancy center",
        "st. john paul ii life center",
        "still waters",
        "the center ",
        "the center",
        "the life center",
        "the open door pregnancy center",
        "the open door",
        "the pregnancy center of the coastal bend",
        "the pregnancy resource center",
        "the source austin",
        "the source for women",
        "the women's clinic of grapevine",
        "thrive women's clinic",
        "tomball pregnancy center",
        "trotter house",
        "truchoice pregnancy center",
        "true options pregnancy center",
        "uptown women's center",
        "waller pregnancy care center",
        "white rose women's center",
        "wise choices pregnancy center",
        "woman to woman pregnancy resource center",
        "women's choice resource center",
        "women's pregnancy center",
    ]
